// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0-devel
// 	protoc        v4.25.4
// source: secure_aggregation.proto

package __

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Share message represents a part of the secret and the sender's identity
type Share struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Part int64  `protobuf:"varint,1,opt,name=part,proto3" json:"part,omitempty"` // The part of the secret being sent
	From string `protobuf:"bytes,2,opt,name=from,proto3" json:"from,omitempty"`  // Identifier for the sender
	To   string `protobuf:"bytes,3,opt,name=to,proto3" json:"to,omitempty"`      // Indentifier recivier
}

func (x *Share) Reset() {
	*x = Share{}
	if protoimpl.UnsafeEnabled {
		mi := &file_secure_aggregation_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Share) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Share) ProtoMessage() {}

func (x *Share) ProtoReflect() protoreflect.Message {
	mi := &file_secure_aggregation_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Share.ProtoReflect.Descriptor instead.
func (*Share) Descriptor() ([]byte, []int) {
	return file_secure_aggregation_proto_rawDescGZIP(), []int{0}
}

func (x *Share) GetPart() int64 {
	if x != nil {
		return x.Part
	}
	return 0
}

func (x *Share) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *Share) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

type ShareOut struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	From string `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	To   string `protobuf:"bytes,2,opt,name=to,proto3" json:"to,omitempty"`
	Data int64  `protobuf:"varint,3,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *ShareOut) Reset() {
	*x = ShareOut{}
	if protoimpl.UnsafeEnabled {
		mi := &file_secure_aggregation_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ShareOut) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShareOut) ProtoMessage() {}

func (x *ShareOut) ProtoReflect() protoreflect.Message {
	mi := &file_secure_aggregation_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShareOut.ProtoReflect.Descriptor instead.
func (*ShareOut) Descriptor() ([]byte, []int) {
	return file_secure_aggregation_proto_rawDescGZIP(), []int{1}
}

func (x *ShareOut) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *ShareOut) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *ShareOut) GetData() int64 {
	if x != nil {
		return x.Data
	}
	return 0
}

type Ack struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *Ack) Reset() {
	*x = Ack{}
	if protoimpl.UnsafeEnabled {
		mi := &file_secure_aggregation_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Ack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ack) ProtoMessage() {}

func (x *Ack) ProtoReflect() protoreflect.Message {
	mi := &file_secure_aggregation_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ack.ProtoReflect.Descriptor instead.
func (*Ack) Descriptor() ([]byte, []int) {
	return file_secure_aggregation_proto_rawDescGZIP(), []int{2}
}

func (x *Ack) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetAddedSharesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Participant string `protobuf:"bytes,1,opt,name=participant,proto3" json:"participant,omitempty"`
}

func (x *GetAddedSharesRequest) Reset() {
	*x = GetAddedSharesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_secure_aggregation_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAddedSharesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAddedSharesRequest) ProtoMessage() {}

func (x *GetAddedSharesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_secure_aggregation_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAddedSharesRequest.ProtoReflect.Descriptor instead.
func (*GetAddedSharesRequest) Descriptor() ([]byte, []int) {
	return file_secure_aggregation_proto_rawDescGZIP(), []int{3}
}

func (x *GetAddedSharesRequest) GetParticipant() string {
	if x != nil {
		return x.Participant
	}
	return ""
}

type GetAddedSharesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AddedShares int64 `protobuf:"varint,1,opt,name=addedShares,proto3" json:"addedShares,omitempty"`
}

func (x *GetAddedSharesResponse) Reset() {
	*x = GetAddedSharesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_secure_aggregation_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAddedSharesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAddedSharesResponse) ProtoMessage() {}

func (x *GetAddedSharesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_secure_aggregation_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAddedSharesResponse.ProtoReflect.Descriptor instead.
func (*GetAddedSharesResponse) Descriptor() ([]byte, []int) {
	return file_secure_aggregation_proto_rawDescGZIP(), []int{4}
}

func (x *GetAddedSharesResponse) GetAddedShares() int64 {
	if x != nil {
		return x.AddedShares
	}
	return 0
}

type GetAddedOutRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Participant string `protobuf:"bytes,1,opt,name=participant,proto3" json:"participant,omitempty"`
}

func (x *GetAddedOutRequest) Reset() {
	*x = GetAddedOutRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_secure_aggregation_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAddedOutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAddedOutRequest) ProtoMessage() {}

func (x *GetAddedOutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_secure_aggregation_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAddedOutRequest.ProtoReflect.Descriptor instead.
func (*GetAddedOutRequest) Descriptor() ([]byte, []int) {
	return file_secure_aggregation_proto_rawDescGZIP(), []int{5}
}

func (x *GetAddedOutRequest) GetParticipant() string {
	if x != nil {
		return x.Participant
	}
	return ""
}

type GetAddedOutResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AddedOut int64 `protobuf:"varint,1,opt,name=addedOut,proto3" json:"addedOut,omitempty"`
}

func (x *GetAddedOutResponse) Reset() {
	*x = GetAddedOutResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_secure_aggregation_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAddedOutResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAddedOutResponse) ProtoMessage() {}

func (x *GetAddedOutResponse) ProtoReflect() protoreflect.Message {
	mi := &file_secure_aggregation_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAddedOutResponse.ProtoReflect.Descriptor instead.
func (*GetAddedOutResponse) Descriptor() ([]byte, []int) {
	return file_secure_aggregation_proto_rawDescGZIP(), []int{6}
}

func (x *GetAddedOutResponse) GetAddedOut() int64 {
	if x != nil {
		return x.AddedOut
	}
	return 0
}

var File_secure_aggregation_proto protoreflect.FileDescriptor

var file_secure_aggregation_proto_rawDesc = []byte{
	0x0a, 0x18, 0x73, 0x65, 0x63, 0x75, 0x72, 0x65, 0x5f, 0x61, 0x67, 0x67, 0x72, 0x65, 0x67, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x3f, 0x0a, 0x05, 0x53, 0x68,
	0x61, 0x72, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x72, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x04, 0x70, 0x61, 0x72, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x66, 0x72, 0x6f, 0x6d, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x66, 0x72, 0x6f, 0x6d, 0x12, 0x0e, 0x0a, 0x02, 0x74,
	0x6f, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x74, 0x6f, 0x22, 0x42, 0x0a, 0x08, 0x53,
	0x68, 0x61, 0x72, 0x65, 0x4f, 0x75, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x66, 0x72, 0x6f, 0x6d, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x66, 0x72, 0x6f, 0x6d, 0x12, 0x0e, 0x0a, 0x02, 0x74,
	0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x74, 0x6f, 0x12, 0x12, 0x0a, 0x04, 0x64,
	0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22,
	0x1f, 0x0a, 0x03, 0x41, 0x63, 0x6b, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x22, 0x39, 0x0a, 0x15, 0x47, 0x65, 0x74, 0x41, 0x64, 0x64, 0x65, 0x64, 0x53, 0x68, 0x61, 0x72,
	0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x20, 0x0a, 0x0b, 0x70, 0x61, 0x72,
	0x74, 0x69, 0x63, 0x69, 0x70, 0x61, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b,
	0x70, 0x61, 0x72, 0x74, 0x69, 0x63, 0x69, 0x70, 0x61, 0x6e, 0x74, 0x22, 0x3a, 0x0a, 0x16, 0x47,
	0x65, 0x74, 0x41, 0x64, 0x64, 0x65, 0x64, 0x53, 0x68, 0x61, 0x72, 0x65, 0x73, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x61, 0x64, 0x64, 0x65, 0x64, 0x53, 0x68,
	0x61, 0x72, 0x65, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0b, 0x61, 0x64, 0x64, 0x65,
	0x64, 0x53, 0x68, 0x61, 0x72, 0x65, 0x73, 0x22, 0x36, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x41, 0x64,
	0x64, 0x65, 0x64, 0x4f, 0x75, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x20, 0x0a,
	0x0b, 0x70, 0x61, 0x72, 0x74, 0x69, 0x63, 0x69, 0x70, 0x61, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0b, 0x70, 0x61, 0x72, 0x74, 0x69, 0x63, 0x69, 0x70, 0x61, 0x6e, 0x74, 0x22,
	0x31, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x41, 0x64, 0x64, 0x65, 0x64, 0x4f, 0x75, 0x74, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x61, 0x64, 0x64, 0x65, 0x64, 0x4f,
	0x75, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x61, 0x64, 0x64, 0x65, 0x64, 0x4f,
	0x75, 0x74, 0x32, 0xd1, 0x01, 0x0a, 0x14, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74, 0x53, 0x68, 0x61,
	0x72, 0x69, 0x6e, 0x67, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x53,
	0x65, 0x6e, 0x64, 0x53, 0x68, 0x61, 0x72, 0x65, 0x12, 0x06, 0x2e, 0x53, 0x68, 0x61, 0x72, 0x65,
	0x1a, 0x04, 0x2e, 0x41, 0x63, 0x6b, 0x22, 0x00, 0x12, 0x1f, 0x0a, 0x0c, 0x53, 0x65, 0x6e, 0x64,
	0x53, 0x68, 0x61, 0x72, 0x65, 0x4f, 0x75, 0x74, 0x12, 0x09, 0x2e, 0x53, 0x68, 0x61, 0x72, 0x65,
	0x4f, 0x75, 0x74, 0x1a, 0x04, 0x2e, 0x41, 0x63, 0x6b, 0x12, 0x41, 0x0a, 0x0e, 0x47, 0x65, 0x74,
	0x41, 0x64, 0x64, 0x65, 0x64, 0x53, 0x68, 0x61, 0x72, 0x65, 0x73, 0x12, 0x16, 0x2e, 0x47, 0x65,
	0x74, 0x41, 0x64, 0x64, 0x65, 0x64, 0x53, 0x68, 0x61, 0x72, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x64, 0x64, 0x65, 0x64, 0x53, 0x68,
	0x61, 0x72, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x38, 0x0a, 0x0b,
	0x47, 0x65, 0x74, 0x41, 0x64, 0x64, 0x65, 0x64, 0x4f, 0x75, 0x74, 0x12, 0x13, 0x2e, 0x47, 0x65,
	0x74, 0x41, 0x64, 0x64, 0x65, 0x64, 0x4f, 0x75, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x14, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x64, 0x64, 0x65, 0x64, 0x4f, 0x75, 0x74, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x04, 0x5a, 0x02, 0x2e, 0x2f, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_secure_aggregation_proto_rawDescOnce sync.Once
	file_secure_aggregation_proto_rawDescData = file_secure_aggregation_proto_rawDesc
)

func file_secure_aggregation_proto_rawDescGZIP() []byte {
	file_secure_aggregation_proto_rawDescOnce.Do(func() {
		file_secure_aggregation_proto_rawDescData = protoimpl.X.CompressGZIP(file_secure_aggregation_proto_rawDescData)
	})
	return file_secure_aggregation_proto_rawDescData
}

var file_secure_aggregation_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_secure_aggregation_proto_goTypes = []interface{}{
	(*Share)(nil),                  // 0: Share
	(*ShareOut)(nil),               // 1: ShareOut
	(*Ack)(nil),                    // 2: Ack
	(*GetAddedSharesRequest)(nil),  // 3: GetAddedSharesRequest
	(*GetAddedSharesResponse)(nil), // 4: GetAddedSharesResponse
	(*GetAddedOutRequest)(nil),     // 5: GetAddedOutRequest
	(*GetAddedOutResponse)(nil),    // 6: GetAddedOutResponse
}
var file_secure_aggregation_proto_depIdxs = []int32{
	0, // 0: SecretSharingService.SendShare:input_type -> Share
	1, // 1: SecretSharingService.SendShareOut:input_type -> ShareOut
	3, // 2: SecretSharingService.GetAddedShares:input_type -> GetAddedSharesRequest
	5, // 3: SecretSharingService.GetAddedOut:input_type -> GetAddedOutRequest
	2, // 4: SecretSharingService.SendShare:output_type -> Ack
	2, // 5: SecretSharingService.SendShareOut:output_type -> Ack
	4, // 6: SecretSharingService.GetAddedShares:output_type -> GetAddedSharesResponse
	6, // 7: SecretSharingService.GetAddedOut:output_type -> GetAddedOutResponse
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_secure_aggregation_proto_init() }
func file_secure_aggregation_proto_init() {
	if File_secure_aggregation_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_secure_aggregation_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Share); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_secure_aggregation_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ShareOut); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_secure_aggregation_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Ack); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_secure_aggregation_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAddedSharesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_secure_aggregation_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAddedSharesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_secure_aggregation_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAddedOutRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_secure_aggregation_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAddedOutResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_secure_aggregation_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_secure_aggregation_proto_goTypes,
		DependencyIndexes: file_secure_aggregation_proto_depIdxs,
		MessageInfos:      file_secure_aggregation_proto_msgTypes,
	}.Build()
	File_secure_aggregation_proto = out.File
	file_secure_aggregation_proto_rawDesc = nil
	file_secure_aggregation_proto_goTypes = nil
	file_secure_aggregation_proto_depIdxs = nil
}
